name: Dizipal 2026 Scraper

on:
  workflow_dispatch: # Manuel başlatmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: |
          pip install seleniumbase
          sbase install chromedriver

      - name: Scraper'ı Çalıştır
        run: python scraper.py

      - name: Sonuçları Yükle (Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dizipal-verileri
          path: |
            sonuc.html
            hata_debug.png
            hata_bulunamadi.png
            hata_sayfa_kaynagi.html
