name: Dizipal Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: |
          pip install seleniumbase
          sbase install chromedriver

      - name: Scripti Çalıştır
        run: python scraper.py

      - name: Dosyaları Kaydet
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dizipal-verileri
          path: |
            sonuc.html
            son_durum.png
            hata_debug.png
            hata_sayfasi.html
