name: Mac Botu Otomasyonu

on:
  schedule:
    # Her 5 dakikada bir çalıştır (Cron formatı)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Manuel çalıştırmak istersen buton çıkarır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu kopyala
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Kütüphaneleri Kur
      run: |
        pip install -r requirements.txt

    - name: Botu Çalıştır
      run: python bot.py

    - name: Veriyi GitHub'a Geri Yükle
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add maclar.json
        git commit -m "Güncel Maç Listesi: $(date)" || exit 0
        git push
